platform :ios, '15.0'

target 'ChatDemo' do
  use_frameworks! :linkage => :static
  
  pod 'AtomicX/Chat', :path => '../../atomic-x/AtomicX.podspec'
  pod 'ChatUIKit', :path => '../uikit/ChatUIKit.podspec'
  pod 'AtomicXCore', '4.2.4'
  pod 'TIMPush', '9.0.7652'
  pod 'TXIMSDK_Plus_iOS_XCFramework', '9.0.7661'

end

target 'pushservice' do
  use_frameworks! :linkage => :static
  
  pod 'TIMPush', '9.0.7652'
end

#Pods config
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          
            config.build_settings['SWIFT_VERSION'] = '5.0'
          
            #Do not strip Swift symbols
            config.build_settings['STRIP_SWIFT_SYMBOLS'] = 'NO'
            config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
          
            #Fix Xcode14 Bundle target error
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
            config.build_settings['ENABLE_BITCODE'] = "NO"
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = "15.0"
            
        end
    end
    
    # Fix resource script issues for pushservice extension
    # Notification Service Extension should not copy privacy bundles
    # Clear the resource script content to skip resource copying
    resources_script = File.join(installer.sandbox.root, 'Target Support Files/Pods-pushservice/Pods-pushservice-resources.sh')
    if File.exist?(resources_script)
        File.write(resources_script, "#!/bin/sh\n# Resources disabled for Notification Service Extension\nexit 0\n")
        puts "Disabled resource copying for Pods-pushservice target"
    end
end

